name: SimpleDragon
description: A sample web application
dependencies:
  browser: any
  route_hierarchical: any
  widget:
    git:
      ref: master
      url: https://github.com/dart-lang/widget.dart.git
